### 1. List services
GET http://localhost:3000/services
Cookie: access_token=REPLACE_WITH_ACCESS_TOKEN

### 2. Get service by id
GET http://localhost:3000/services/REPLACE_WITH_SERVICE_ID
Cookie: access_token=REPLACE_WITH_ACCESS_TOKEN

### 3. Create service
POST http://localhost:3000/services
Content-Type: application/json
Cookie: access_token=REPLACE_WITH_ACCESS_TOKEN

{
  "name": "Corte de cabello",
  "description": "Haircut service",
  "base_price": 15
}

### 4. Update service
PUT http://localhost:3000/services/REPLACE_WITH_SERVICE_ID
Content-Type: application/json
Cookie: access_token=REPLACE_WITH_ACCESS_TOKEN

{
  "base_price": 18
}

### 5. Delete service
DELETE http://localhost:3000/services/REPLACE_WITH_SERVICE_ID
Cookie: access_token=REPLACE_WITH_ACCESS_TOKEN